version: '3.5'

services:
  stock-db:
    container_name: stock-db
    image: postgres:13-alpine
    ports:
      - "5439:5432"
    environment:
      - POSTGRES_DB=stock-db
      - POSTGRES_PASSWORD=stock
      - POSTGRES_USER=stock
    volumes:
      - stock_vol:/var/lib/postgresql/data